posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^myposts$', views.my_posts, name='myposts'),
    url(r'^create/$', views.post_create),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
    
]

trydjango19/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('posts.urls', namespace="posts")),
    url(r'^accounts/logout/$', views.logout, {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.conf import settings

from django.utils.text import slugify

import datetime
# Create your models here.

def upload_location(instance, filename):
    actual_date = datetime.date.today()
    return "%s/%s" %(actual_date, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
        null = True,
        blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)

    def __unicode__(self):
        return self.title


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = [ '-timestamp', '-updated' ]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]
        forms.DateInput.input_type="date"

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib import quote_plus
from django.utils import timezone

# Create your views here.

from .models import Post
from .forms import PostForm


def post_list(request):
    queryset_list = Post.objects.filter(draft=False).filter(publish__lte=timezone.now())
    #queryset = Post.objects.all().order_by("-timestamp")

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(title__icontains=query)

    paginator = Paginator(queryset_list, 2) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "queryset": queryset,
        "queryset_list_len": len(queryset_list),
        "title": "All posts"
    }
    return render(request, 'post_list.html', context)
    
@login_required
def my_posts(request):
    
    username = request.user.id
    queryset_list = Post.objects.filter(user=username)
    
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(title__icontains=query)
    
    paginator = Paginator(queryset_list, 2) # Show 25 contacts per page
    
    page = request.GET.get('page')
    queryset = queryset_list
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
        
    context = {
        "queryset": queryset,
        "queryset_list_len": len(queryset_list),
        "title": "Your posts"
    }
    return render(request, 'post_list.html', context)

def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    absolute_url = request.build_absolute_uri
    share_url = quote_plus(instance.content)
    context = {
        "instance": instance,
        "title": instance.title,
        "absolute_url": absolute_url,
        "share_url": share_url
    }
    return render(request, 'post_detail.html', context)

@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully created new post")
        return HttpResponseRedirect(instance.get_absolute_url())
    submit_button = 'Create'
    context = {
        'form': form,
        'submit_button': submit_button,
    }

    return render(request, 'post_form.html', context)

def post_update(request, slug=None):

    instance = get_object_or_404(Post, slug=slug)

    if instance.user != request.user:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully updated post: " + instance.title)
        return HttpResponseRedirect(instance.get_absolute_url())
    submit_button = 'Update'
    context = {
        "title": instance.title,
        "instance": instance,
        'form': form,
        'submit_button': submit_button,
    }
    return render(request, 'post_form.html', context)

def post_delete(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)

    if instance.user != request.user:
        raise Http404

    instance.delete()
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
    crossorigin="anonymous" />

    <!-- Optional theme -->
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
    integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r"
    crossorigin="anonymous">

    <!-- Font awesome -->
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href='{% static "css/base.css" %}' />

    <title>{% block head %} My blog {% endblock %} </title>
  </head>
  <body>
    {% include "messages.html" %}
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'posts:list' %}">
            Django Blog
          </a>
        </div>
        <div class="navbar-form navbar-right">
          <div class="navbar-collapse collapse">
             {% if user.is_authenticated %}
               <span>Logged in as {{ request.user.get_full_name }}</span>
      
               {% if user.socialaccount_set.all.0.get_avatar_url %}
                  <img class="imgPerfil" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />
               {% else %}
                  <img class="imgPerfil" src="{% static 'images/default.png' %}" />
               {% endif %}
               <a id="logout" href="/accounts/logout" class="btn btn-warning">Logout</a>
             {% else %}
               <a id="google_login" href="/accounts/google/login" class="btn btn-success">
                 Sign in with Google
               </a>
             {% endif %}
           </div>
         </div>
      </div>
      
    </nav>
    
    <div class='container'>
        {% block content %}

        {% endblock %}
    </div>
  </body>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
  integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
  crossorigin="anonymous"></script>
</html>

templates/messages.html
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}

{% block head %}
  {{ instance.title }} - {{ block.super }}
{% endblock %}

{% block content %}
  <div class="col-sm-8 col-sm-offset-2">
    {% if instance.image %}
      <img src="{{ instance.image.url }}" class="img-responsive" />
    {% endif %}
    <h2>{{ title }}
      {% if instance.draft %}  
        <small class="draft">Draft</small>
      {% endif %}
      <small>{{ instance.publish }}</small>
    </h2>
    {% if instance.user.get_full_name %}
      <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}
    
    <div>
      <h5>Share on:</h5>
      <a href="https://twitter.com/home?status={{ share_url }}%20{{ absolute_url }}">
        <i class="socialLink twitterShare fa fa-twitter"></i>
      </a>

      <a href='https://plus.google.com/share?url={{ absolute_url }}'>
        <i class="socialLink googleShare fa fa-google-plus"></i>
      </a>
    </div>

    <hr/>

    {{ instance.content|linebreaks }}<br/>
    <hr/>

  </div>
{% endblock %}

templates/post_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
  <h1> Form </h1>

  <form method="POST" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{ form|bootstrap }}
    <input type="submit" class="btn btn-default" value={{ submit_button }} />
  </form>
</div>
{% endblock %}

templates/post_list.html
{% extends "base.html" %}

{% block content %}
  <div class="col-sm-8 col-sm-offset-2">
    <h1>{{ title }} 
      <small>
          {% if title == 'Your posts' %}
            <a href="{% url 'posts:list' %}">All posts</a>
          {% else %}
            <a href="{% url 'posts:myposts' %}">Your posts</a>
          {% endif %}
      </small>
    </h1>
    
    <hr/>
    <div class="row"> 
      <div class="col-sm-8">  
        <form method="GET" action="">
          <div class="input-group">
            <input value="{{ request.GET.q }}" name="q" class="form-control" type="text" placeholder="Search posts" />
            <span class="input-group-btn">
              <input type="submit" class="btn btn-default" value="Search" />
            </span>
          </div>
        </form>
      </div>
    </div>
    <hr/>
    
    <div class="row"> 
      {% for post in queryset %}
      <div class="col-sm-12">
        <div class="thumbnail">
          {% if post.image %}
            <img src="{{ post.image.url }}">
          {% endif %}
          <div class="caption">
            <h3>
              <a href="{{ post.get_absolute_url }}" >{{ post.title }}</a><br/>
              <small>{{ post.timestamp|timesince }} ago</small>
            </h3>
            {% if post.user.get_full_name %}
              <p>Author: {{ post.user.get_full_name }}</p>
            {% endif %}
            <p>{{ post.content|linebreaks|truncatechars:50 }}</p>
            {% if post.user.get_full_name == user.socialaccount_set.all.0.extra_data.name or post.user.get_full_name == request.user.get_full_name %}
              <p>
                <a href="{{ post.get_absolute_url }}edit" class="btn btn-primary" role="button">Edit</a>
                <a href="{{ post.get_absolute_url }}delete" class="btn btn-danger" role="button">Delete</a>
              </p>
            {% endif %}
          </div>
        </div>
      </div>

      <!--
        {% cycle "" "<div class='col-sm-12'></hr></div> </div><div class='row'>" %}
      -->
    </hr>
    {% empty %}
    <div class="text-center">
      {% if not request.GET.q %}
        {% if user.is_authenticated %}
            <div class="h4">You do not have any posts:</div>
            <a href="create" class="btn btn-primary" role="button">Create your first now!</a>
        {% else %}
            <div class="h4">Well... This is awkward. 
              <br/>
              There are no posts, and, as long you are not logged in, you cannot create one...
              <br/>
              <br/>
              <b>What are you waiting for?</b>
              <br/> 
              <a id="google_login" href="/accounts/google/login" class="btn btn-default">
                Logging in now <i class="googleShare fa fa-google-plus"></i>
              </a>
            </div>
        {% endif %}
      {% else %}
        <div>No posts found containing: <b>{{ request.GET.q }}</b></div>
      {% endif %}
    </div>
  {% endfor %}
  </div>
  <!--<div class="pagination">
      <span class="step-links">
          {% if queryset.has_previous %}
              <a href="?page={{ queryset.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
          </span>

          {% if queryset.has_next %}
              <a href="?page={{ queryset.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>-->
  {% if queryset_list_len != 0 %}
    <div class="text-center">
      {% for num in queryset.paginator.page_range %}
        {% ifequal num queryset.number %}
          <span class="btn btn-info">{{ num }}</span>
        {% else %}
          <a href="?page={{ num }}&q={{ request.GET.q }}" class="btn btn-default"> {{ num }}</a>
        {% endifequal %}
      {% endfor %}
    </div>
  {% endif %}



</div>
{% endblock %}



</div>